# Generated by Django 5.1.6 on 2025-03-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_case_price_remove_graphiccard_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
