# Generated by Django 5.1.6 on 2025-03-13 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_offer_content_type_remove_offer_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_offers', to='store.case'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='graphic_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graphic_card_offers', to='store.graphiccard'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='motherboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_offers', to='store.motherboard'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='power_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power_supply_offers', to='store.powersupply'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processor_offers', to='store.processor'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ram_offers', to='store.ram'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_offers', to='store.storage'),
        ),
    ]
